name: cheminformatics_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - notebook
  - rdkit
  - tensorflow
  - pytorch
  - torchvision
  - torchaudio
  - xgboost
  - python-dotenv
  - pip
  - pip:
      - requests
      - tqdm
      - py3Dmol
      - biopandas
      - molsets
      - huggingface_hub
      - transformers
      - fair-esm
      - jax
      - jaxtyping
      - beartype
