name: cheminformatics_project
channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  - python=3.10
  - numpy<2.0
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - jupyterlab
  - notebook
  - rdkit
  - xgboost
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - python-dotenv
  - pip:
      - tf_keras
      - deepchem==2.7.1
      - torch-geometric
      - dgl
      - py3Dmol
      - biopandas
      - molsets
      - huggingface_hub
      - transformers
      - fair-esm
      - jax
      - jaxtyping
      - beartype
